export function getRequiredElement<T extends Element>(selector: string): T {
  const element = document.querySelector<T>(selector);
  if (!element) throw new Error(`Missing required element: ${selector}`);
  return element;
}

export const dom = {
  applyPreferencesButton: getRequiredElement<HTMLButtonElement>("#apply-preferences"),
  avatarButton: getRequiredElement<HTMLButtonElement>(".avatar-button"),
  budgetSetting: getRequiredElement<HTMLSelectElement>("#budget-setting"),
  clearDataButton: getRequiredElement<HTMLButtonElement>("#clear-data-button"),
  connectionStatus: getRequiredElement<HTMLDivElement>("#connection-status"),
  currentLocationChip: getRequiredElement<HTMLParagraphElement>("#current-location-chip"),
  currentSearchMaps: getRequiredElement<HTMLAnchorElement>("#current-search-maps"),
  debugEndpoint: getRequiredElement<HTMLElement>("#debug-endpoint"),
  debugProvider: getRequiredElement<HTMLElement>("#debug-provider"),
  debugRadius: getRequiredElement<HTMLElement>("#debug-radius"),
  debugResults: getRequiredElement<HTMLElement>("#debug-results"),
  debugVersion: getRequiredElement<HTMLElement>("#debug-version"),
  developerModeSetting: getRequiredElement<HTMLInputElement>("#developer-mode-setting"),
  developerPanel: getRequiredElement<HTMLElement>("#developer-panel"),
  detailClose: getRequiredElement<HTMLButtonElement>("#detail-close"),
  detailContent: getRequiredElement<HTMLDivElement>("#detail-content"),
  detailDialog: getRequiredElement<HTMLDialogElement>("#detail-dialog"),
  dishInput: getRequiredElement<HTMLInputElement>("#dish-input"),
  distanceFilter: getRequiredElement<HTMLSelectElement>("#distance-filter"),
  foodPreferenceInputs: document.querySelectorAll<HTMLInputElement>("[name='food-preference']"),
  handoffSetting: getRequiredElement<HTMLInputElement>("#handoff-setting"),
  languageSetting: getRequiredElement<HTMLSelectElement>("#language-setting"),
  locationButton: getRequiredElement<HTMLButtonElement>("#location-button"),
  locationDetail: getRequiredElement<HTMLParagraphElement>("#location-detail"),
  locationInput: getRequiredElement<HTMLInputElement>("#location-input"),
  locationSuggestions: getRequiredElement<HTMLDivElement>("#location-suggestions"),
  locationTitle: getRequiredElement<HTMLElement>("#location-title"),
  mapFrame: getRequiredElement<HTMLIFrameElement>("#map-frame"),
  mapsModeSetting: getRequiredElement<HTMLSelectElement>("#maps-mode-setting"),
  mapPlaceList: getRequiredElement<HTMLDivElement>("#map-place-list"),
  navButtons: document.querySelectorAll<HTMLButtonElement>("[data-nav-view]"),
  priceFilter: getRequiredElement<HTMLSelectElement>("#price-filter"),
  radiusSetting: getRequiredElement<HTMLSelectElement>("#radius-setting"),
  resultCount: getRequiredElement<HTMLElement>("#result-count"),
  resultsList: getRequiredElement<HTMLDivElement>("#results-list"),
  searchButton: getRequiredElement<HTMLButtonElement>("#search-button"),
  selectedSummary: getRequiredElement<HTMLDivElement>("#selected-summary"),
  sortFilter: getRequiredElement<HTMLSelectElement>("#sort-filter"),
  views: document.querySelectorAll<HTMLElement>(".app-view"),
};
